config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/choice'
  devise_for :users
  get '/search' => 'search#search'
  resource :study_counts, only: [:create]
  get '/dangers' => 'dangers#index'
  get '/category' => 'categories#category'

  # collection以降、学習機能実装時、URL要確認
  resources :it_words do
    collection do
      get 'start'
      get 'finish'
      get 'quiz'
      get 'category_quiz'
    end
    member do
      get 'category_show'
    end
    resources :bookmarks, only: %i[create destroy]
    resources :dangers, only: %i[create destroy]
  end

  resources :users, only: %i[index edit update destroy show] do
    member do
      get '/bookmarks' => 'bookmarks#index'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # 引数で渡されたユーザidがBookmarksテーブル内に存在（exists?）するかどうかを調べる
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :it_words, dependent: :destroy
end

app/models/danger.rb
class Danger < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/it_word.rb
class ItWord < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy

  validates :word, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがDangersテーブル内に存在（exists?）するかどうかを調べる
  def dangered_by?(user)
    dangers.where(user_id: user.id).exists?
  end

  # searchの定義
  def self.search(search)
    ItWord.where(['word LIKE ?', "%#{search}%"])
  end
end

app/models/study_count.rb
class StudyCount < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :it_words, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy
  has_many :study_counts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    # js.erbファイルへ渡す必要があるからインスタンス変数
    @it_word = ItWord.find(params[:it_word_id])
    bookmark = current_user.bookmarks.new(it_word_id: @it_word.id)
    bookmark.save
  end

  def destroy
    # js.erbファイルへ渡す必要があるからインスタンス変数
    @it_word = ItWord.find(params[:it_word_id])
    bookmark = current_user.bookmarks.find_by(it_word_id: @it_word.id)
    bookmark.destroy
  end

  def index
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
end

app/controllers/dangers_controller.rb
class DangersController < ApplicationController
  def create
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.new(it_word_id: @it_word.id)
    danger.save
  end

  def destroy
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.find_by(it_word_id: @it_word.id)
    danger.destroy
  end

  def index
    @dangers = Danger.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def choice
    @it_words = ItWord.all
  end
end

app/controllers/it_words_controller.rb
class ItWordsController < ApplicationController
  def new
    @it_word = ItWord.new
    @categories = Category.all
  end

  def create
    # エラーメッセージ表示の為、インスタンス変数
    @it_word = ItWord.new(it_word_params)
    if @it_word.save
      redirect_to it_words_path
    else
      @categories = Category.all
      render 'new'
    end
  end

  def edit
    @it_word = ItWord.find(params[:id])
    @categories = Category.all
  end

  def update
    # エラーメッセージ表示の為、インスタンス変数
    @it_word = ItWord.find(params[:id])
    if @it_word.update(it_word_params)
      redirect_to it_words_path
    else
      @categories = Category.all
      render 'edit'
    end
  end

  def destroy
    it_word = ItWord.find(params[:id])
    it_word.destroy
    redirect_back(fallback_location: root_path)
  end

  # カテゴリー無しver
  def quiz
    quiz = Rails.cache.read('quiz') || '[]'
    quiz = JSON.parse(quiz)
    if quiz.blank?
      # ランダムにレコード取得
      random = ItWord.order('RAND()')
      # ●"quiz"に定義●"to_json"にて文字列として保存
      Rails.cache.write('quiz', random.to_json)
    end
    word = Rails.cache.read('quiz')
    # ●再び配列へ●wordを置き換えてるので下記変数名である必要がある
    word = JSON.parse word
    @random = word.first
    word.delete_if { |w| w['id'] == @random['id'] }
    Rails.cache.write('quiz', word.to_json)
  end

  # カテゴリー有りver
  def category_quiz
    @category = Category.find_by(category: params[:category])
    quiz = Rails.cache.read('quiz') || '[]'
    quiz = JSON.parse(quiz)
    if quiz.blank?
      # ランダムにレコード取得
      random = @category.it_words.order('RAND()')
      # ●"quiz"に定義●"to_json"にて文字列として保存
      Rails.cache.write('quiz', random.to_json)
    end
    word = Rails.cache.read('quiz')
    # ●再び配列へ●wordを置き換えてるので下記変数名である必要がある
    word = JSON.parse word
    @random = word.first
    # 一度出たit_wordは削除する
    word.delete_if { |w| w['id'] == @random['id'] }
    # ・"quiz"に定義・"to_json"にて文字列として保存
    Rails.cache.write('quiz', word.to_json)
  end

  # カテゴリー無しver
  def show
    @it_word = ItWord.find(params[:id])
  end

  # カテゴリー有りver
  def category_show
    @it_word = ItWord.find(params[:id])
    @category = Category.find_by(category: params[:category])
  end

  def finish
    @study_count = current_user.study_counts.where(is_study: true).count
    current_user.study_counts.destroy_all
    # キャッシュをクリアする
    Rails.cache.clear
  end

  def index
    # 降順表示、ページネーション
    @it_words = ItWord.order('id ASC').page(params[:page]).reverse_order
  end

  private

  def it_word_params
    params.require(:it_word).permit(:user_id, :word, :body, :category_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @it_words = ItWord.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # エラーメッセージ表示の為、インスタンス変数
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      # 元々のデータ渡す必要が無いから、インスタンス変数渡さなくていい
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/'
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dangers_helper.rb
module DangersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/it_words_helper.rb
module ItWordsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/study_counts_helper.rb
module StudyCountsHelper
end

app/helpers/study_quantities_helper.rb
module StudyQuantitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<% if it_word.bookmarked_by?(current_user) %>
  <%= link_to "♥", it_word_bookmark_path(it_word, it_word.bookmarks), method: :delete, remote: true %>
<% else %>
  <%= link_to "♡", it_word_bookmarks_path(it_word), method: :post, remote: true %>
<% end %>

app/views/bookmarks/create.js.erb
<!--ここでの@it_wordはbookmarkコントローラで渡された変数-->
$("#bookmark_<%= @it_word.id %>").html("<%= j(render 'bookmark', it_word: @it_word) %>");

app/views/bookmarks/destroy.js.erb
<!--ここでの@it_wordはbookmarkコントローラで渡された-->
$("#bookmark_<%= @it_word.id %>").html("<%= j(render 'bookmark', it_word: @it_word) %>");

app/views/bookmarks/index.html.erb
<div class = "container mt-5">
  <h1>【ブックマーク一覧】</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>IT用語</th>
        <th>意味</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @bookmarks.each do |bookmark| %>
        <tr>
          <td><%= bookmark.it_word.word %></td>
          <td><%= bookmark.it_word.body %></td>
          <!--ブックマーク-->
          <td id = "bookmark_<%= bookmark.it_word.id %>" >
            <%= render "bookmarks/bookmark", it_word: bookmark.it_word %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dangers/_danger.html.erb
<% if it_word.dangered_by?(current_user) %>
  <%= link_to "通報を取り消す", it_word_danger_path(it_word, it_word.dangers), method: :delete, remote: true %>
<% else %>
  <%= link_to "通報する", it_word_dangers_path(it_word), method: :post, "data-confirm" => "本当に通報しますか？", remote: true %>
<% end %>

app/views/dangers/create.js.erb
<!--ここでの@it_wordはbookmarkコントローラで渡された変数-->
$("#danger_<%= @it_word.id %>").html("<%= j(render 'danger', it_word: @it_word) %>");

app/views/dangers/destroy.js.erb
<!--ここでの@it_wordはbookmarkコントローラで渡された変数-->
$("#danger_<%= @it_word.id %>").html("<%= j(render 'danger', it_word: @it_word) %>");

app/views/dangers/index.html.erb
<div class = "container mt-5">
  <h1>【通報一覧】</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>通報者</th>
        <th>投稿者</th>
        <th>IT用語</th>
        <th>意味</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @dangers.each do |danger| %>
        <tr>
          <td>
            <%= link_to danger.user.name, user_path(danger.user) %>
          </td>
          <td>
            <%= link_to danger.it_word.user.name, user_path(danger.it_word.user) %>
          </td>
          <td>
            <%= danger.it_word.word %>
          </td>
          <td>
            <%= danger.it_word.body %>
          </td>
          <td>
            <%= link_to "", edit_it_word_path(danger.it_word), class: "fas fa-cog" %>
          </td>
          <td>
            <%= link_to "", it_word_path(danger.it_word), method: :delete, "data-confirm" => "本当に削除しますか？", class: "fas fa-ban" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/it_words/_it-words-index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>IT用語</th>
      <th>意味</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% it_words.each do |it_word| %>
      <tr>
        <td><%= it_word.word %></td>
        <td><%= it_word.body %></td>
        <% if current_user.is_admin? %>
          <td>
            <%= link_to "", edit_it_word_path(it_word), class: "fas fa-cog" %>
          </td>
          <td>
            <%= link_to "", it_word_path(it_word), method: :delete, "data-confirm" => "本当に削除しますか？", class: "fas fa-ban" %>
          </td>
        <% elsif current_user == it_word.user %>
          <td>
            <%= link_to "", edit_it_word_path(it_word), class: "fas fa-cog" %>
          </td>
          <td>
            <%= link_to "", it_word_path(it_word), method: :delete, "data-confirm" => "本当に削除しますか？", class: "fas fa-ban" %>
          </td>
        <% else %>
          <!--ブックマーク-->
          <td id = "bookmark_<%= it_word.id %>" >
            <%= render "bookmarks/bookmark", it_word: it_word %>
          </td>
          <!--通報-->
          <td id = "danger_<%= it_word.id %>" >
            <%= render "dangers/danger", it_word: it_word %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/it_words/category_quiz.html.erb
<div class = "container">
  <main class = "mt-5 d-flex align-items-center justify-content-center">

    <h1 class = "col-6">
      <%= @random["word"] %>
    </h1>

    <button type = "button" class = "col-3 btn btn-outline-secondary mb-1">
      <%= link_to "意味を確認する", study_counts_path(id: @random["id"], category: @category.category), method: :post %>
    </button>
  </main>
</div>

app/views/it_words/category_show.html.erb
<div class = "container mt-5">
  <h1 class = "mx-auto">【IT用語答え】</h1>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th>IT用語</th>
        <th>意味</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @it_word.word %></td>
        <td><%= @it_word.body %></td>
        <!--bookmark機能-->
        <td id = "bookmark_<%= @it_word.id %>" >
          <%= render "bookmarks/bookmark", it_word: @it_word %>
        </td>
        <!--通報機能-->
        <td id = "danger_<%= @it_word.id %>" >
          <%= render "dangers/danger", it_word: @it_word %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class = "text-right">
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "次の用語", category_quiz_it_words_path(category: @category.category) %>
    </button>
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "学習終了", finish_it_words_path %>
    </button>
  </div>
</div>

app/views/it_words/edit.html.erb
<div class = "container">
  <main class = "mt-5 mx-auto pt-5">
    <div class ="col">
      <h1>【IT用語編集画面】</h1>
    </div>

    <!--エラーメッセージ-->
    <% if @it_word.errors.any? %>
      <div class = "text-danger">
        <%= @it_word.errors.count %>件のエラーが発生しました
        <% @it_word.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>

    <div class = "edit-user">
      <%= form_with model: @it_word, local:true do |f| %>
        <h4>IT用語</h4>
        <%= f.text_field :word, value: @it_word.word %>
        <h4>意味</h4>
        <%= f.text_area :body, value: @it_word.body %></br>
        <%= f.collection_select(:category_id, @categories, :id, :category) %></br>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit "IT用語更新する" %>
      <% end %>
    </div>
  </main>
</div>

<div class = "edit-word">

</div>

app/views/it_words/finish.html.erb
<div class = "container">
  <main class = "mt-5 d-flex align-items-center justify-content-center">
    <h1>お疲れ様でした。</h1>
    <h1><%= @study_count %>個、IT用語学習しました。</h1>
  </main>
</div>

app/views/it_words/index.html.erb
<div class = "container mt-5">
  <h1>【IT用語一覧】</h1>

  <h3>↓　カテゴリー別に確認する　↓</h3>
  <button type = "button" class = "btn btn-outline-secondary btn-lg">
    <%= link_to "就活系IT用語", category_path(category: "就活系") %>
  </button>

  <button type = "button" class = "btn btn-outline-secondary btn-lg">
    <%= link_to "プログラミング系IT用語", category_path(category: "プログラミング系") %>
  </button>

  <button type = "button" class = "btn btn-outline-secondary btn-lg">
    <%= link_to "先進技術系IT用語", category_path(category: "先進技術系") %>
  </button>

  <!--it_word一覧の部分テンプレート-->
  <%= render "it_words/it-words-index", it_words: @it_words %>
  <!--ページネーション-->
  <div class = "pagination justify-content-center">
    <%= paginate @it_words %>
  </div>
</div>

app/views/it_words/new.html.erb
<div class = "container mt-5">
  <main class = "mx-auto pt-5">
    <div class ="col">
      <h1>【IT用語登録】</h1>
    </div>

    <!--エラーメッセージ-->
    <% if @it_word.errors.any? %>
      <div class = "text-danger">
        <%= @it_word.errors.count %>件のエラーが発生しました
        <% @it_word.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>

    <!--入力フォーム-->
    <%= form_with model: @it_word, local: true do |f| %>
      <h4>IT用語</h4>
      <%= f.text_field :word %>
      <h4>意味</h4>
      <%= f.text_area :body %></br>
      <%= f.collection_select(:category_id, @categories, :id, :category) %></br>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "IT用語登録する" %>
    <% end %>
  </main>
</div>

app/views/it_words/quiz.html.erb
<div class = "container">
  <main class = "mt-5 d-flex align-items-center justify-content-center">

    <h1 class = "col-6">
      <%= @random["word"] %>
    </h1>

    <button type = "button" class = "col-3 btn btn-outline-secondary mb-1">
      <%= link_to "意味を確認する", study_counts_path(id: @random["id"]), method: :post %>
    </button>
  </main>
</div>

app/views/it_words/show.html.erb
<div class = "container mt-5">
  <h1 class = "mx-auto">【IT用語答え】</h1>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th>IT用語</th>
        <th>意味</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @it_word.word %></td>
        <td><%= @it_word.body %></td>
        <!--bookmark機能-->
        <td id = "bookmark_<%= @it_word.id %>" >
          <%= render "bookmarks/bookmark", it_word: @it_word %>
        </td>
        <!--通報機能-->
        <td id = "danger_<%= @it_word.id %>" >
          <%= render "dangers/danger", it_word: @it_word %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class = "text-right">
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "次の用語", quiz_it_words_path %>
    </button>
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "学習終了", finish_it_words_path %>
    </button>
  </div>
</div>

app/views/it_words/start.html.erb
<div class = "container mt-5">
  <main class = "mx-auto pt-5">
    <div class = "col">
      <h1>【学習スタートする】</h1>
    </div>

    <!--カテゴリー選択-->
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-1">
      <%= link_to "カテゴリーごちゃまぜ", quiz_it_words_path %>
    </button>
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-1">
      <%= link_to "就活系IT用語", category_quiz_it_words_path(category: "就活系") %>
    </button>
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-1">
      <%= link_to "プログラミング系IT用語", category_quiz_it_words_path(category: "プログラミング系") %>
    </button>
    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-1">
      <%= link_to "先進技術系IT用語", category_quiz_it_words_path(category: "先進技術系") %>
    </button>
  </main>
</div>

app/views/users/edit.html.erb
<div class = "container">
  <main class = "mt-5 mx-auto pt-5">
    <div class ="col">
      <h1>【会員情報編集】</h1>
    </div>

    <!--エラーメッセージ-->
    <% if @user.errors.any? %>
      <div class = "text-danger">
        <%= @user.errors.count %>件のエラーが発生しました
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>

    <div class = "edit-user">
      <%= form_with model: @user, local:true do |f| %>
        <h4>名前</h4>
        <%= f.text_field :name, value: @user.name %>
        <h4>メールアドレス</h4>
        <%= f.text_field :email, value: @user.email %></br>
        <%= f.submit "会員情報更新する" %>
      <% end %>
    </div>
  </main>
</div>

app/views/users/index.html.erb
<div class = "container mt-5">
  <h1>【会員一覧】</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>名前</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>

app/views/users/show.html.erb
<main class = "mx-auto mt-5 py-5">
  <h1 class = "mx-auto">【会員詳細】</h1>

  <table class="table table-inverse">
    <thead>
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.name %></td>
        <td><%= @user.email %></td>
        <% if current_user.is_admin? %>
          <td><%= link_to "強制退会する", user_path(@user), "data-confirm" => "本当に強制退会させますか？",method: :delete %></td>
        <% elsif current_user = @user %>
          <td><%= link_to "編集する", edit_user_path(@user) %></td>
          <td><%= link_to "退会する", user_path(@user), "data-confirm" => "本当に退会しますか？", method: :delete %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</main>