config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/choice'
  devise_for :users
  get '/search' => 'search#search'
  resource :study_counts, only: [:create]
  get '/dangers' => 'dangers#index'
  get '/category' => 'categories#category'

  # collection以降、学習機能実装時、URL要確認
  resources :it_words do
    collection do
      get 'start'
      get 'finish'
      get 'quiz'
      get 'category_quiz'
    end
    member do
      get 'category_show'
    end
    resources :bookmarks, only: %i[create destroy]
    resources :dangers, only: %i[create destroy]
  end

  resources :users, only: %i[index edit update destroy show] do
    member do
      get '/bookmarks' => 'bookmarks#index'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # 引数で渡されたユーザidがBookmarksテーブル内に存在（exists?）するかどうかを調べる
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :it_words, dependent: :destroy
end

app/models/danger.rb
class Danger < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/it_word.rb
class ItWord < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy

  validates :word, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがDangersテーブル内に存在（exists?）するかどうかを調べる
  def dangered_by?(user)
    dangers.where(user_id: user.id).exists?
  end

  # searchの定義
  def self.search(search)
    ItWord.where(['word LIKE ?', "%#{search}%"])
  end
end

app/models/study_count.rb
class StudyCount < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :it_words, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy
  has_many :study_counts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/dangers_controller.rb
class DangersController < ApplicationController
  def create
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.new(it_word_id: @it_word.id)
    danger.save
  end

  def destroy
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.find_by(it_word_id: @it_word.id)
    danger.destroy
  end

  def index
    @dangers = Danger.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def choice
    @it_words = ItWord.all
  end
end

app/controllers/it_words_controller.rb
class ItWordsController < ApplicationController
  def new
    @it_word = ItWord.new
    @categories = Category.all
  end

  def create
    # エラーメッセージ表示の為、インスタンス変数
    @it_word = ItWord.new(it_word_params)
    if @it_word.save
      redirect_to it_words_path
    else
      @categories = Category.all
      render 'new'
    end
  end

  def edit
    @it_word = ItWord.find(params[:id])
    @categories = Category.all
  end

  def update
    # エラーメッセージ表示の為、インスタンス変数
    @it_word = ItWord.find(params[:id])
    if @it_word.update(it_word_params)
      redirect_to it_words_path
    else
      @categories = Category.all
      render 'edit'
    end
  end

  def destroy
    it_word = ItWord.find(params[:id])
    it_word.destroy
    redirect_back(fallback_location: root_path)
  end

  # カテゴリー無しver
  def quiz
    quiz = Rails.cache.read('quiz') || '[]'
    quiz = JSON.parse(quiz)
    if quiz.blank?
      # ランダムにレコード取得
      random = ItWord.order('RAND()')
      # ●"quiz"に定義●"to_json"にて文字列として保存
      Rails.cache.write('quiz', random.to_json)
    end
    word = Rails.cache.read('quiz')
    # ●再び配列へ●wordを置き換えてるので下記変数名である必要がある
    word = JSON.parse word
    @random = word.first
    word.delete_if { |w| w['id'] == @random['id'] }
    Rails.cache.write('quiz', word.to_json)
  end

  # カテゴリー有りver
  def category_quiz
    @category = Category.find_by(category: params[:category])
    quiz = Rails.cache.read('quiz') || '[]'
    quiz = JSON.parse(quiz)
    if quiz.blank?
      # ランダムにレコード取得
      random = @category.it_words.order('RAND()')
      # ●"quiz"に定義●"to_json"にて文字列として保存
      Rails.cache.write('quiz', random.to_json)
    end
    word = Rails.cache.read('quiz')
    # ●再び配列へ●wordを置き換えてるので下記変数名である必要がある
    word = JSON.parse word
    @random = word.first
    # 一度出たit_wordは削除する
    word.delete_if { |w| w['id'] == @random['id'] }
    # ・"quiz"に定義・"to_json"にて文字列として保存
    Rails.cache.write('quiz', word.to_json)
  end

  # カテゴリー無しver
  def show
    @it_word = ItWord.find(params[:id])
  end

  # カテゴリー有りver
  def category_show
    @it_word = ItWord.find(params[:id])
    @category = Category.find_by(category: params[:category])
  end

  def finish
    @study_count = current_user.study_counts.where(is_study: true).count
    current_user.study_counts.destroy_all
    # キャッシュをクリアする
    Rails.cache.clear
  end

  def index
    # 降順表示、ページネーション
    @it_words = ItWord.order('id ASC').page(params[:page]).reverse_order
  end

  private

  def it_word_params
    params.require(:it_word).permit(:user_id, :word, :body, :category_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @it_words = ItWord.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # エラーメッセージ表示の為、インスタンス変数
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      # 元々のデータ渡す必要が無いから、インスタンス変数渡さなくていい
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/'
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dangers_helper.rb
module DangersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/it_words_helper.rb
module ItWordsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/study_counts_helper.rb
module StudyCountsHelper
end

app/helpers/study_quantities_helper.rb
module StudyQuantitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/choice.html.erb
<main class = "mx-auto mt-5 py-5">
  <% if current_user.is_admin? %>

    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "通報を確認する", dangers_path %>
    </button>

    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "会員一覧", users_path %>
    </button>

    <div class = "search mb-5">
      <h4>検索する</h4>
      <%= form_with url: "/search", method: :get, local: true do |f| %>
        <%= f.text_field :search %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

    <h4>新着IT用語</h4>
    <!--新着用語５件表示-->
    <% @it_words.last(5).each do |it_word| %>
      ★<%= it_word.word %>
    <% end %>

  <% else %>

    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "学習モード", start_it_words_path %>
    </button>

    <button type = "button" class = "btn btn-outline-secondary btn-lg mb-5">
      <%= link_to "復習モード", bookmarks_user_path(current_user) %>
    </button>

    <div class = "search mb-5">
      <h4>検索モード</h4>
      <%= form_with url: "/search", method: :get, local: true do |f| %>
        <%= f.text_field :search %>
        <%= f.submit "検索" %>
      <% end %>
    </div>

    <h4>新着IT用語</h4>
    <!--新着用語５件表示-->
    <% @it_words.last(5).each do |it_word| %>
      ★<%= it_word.word %>
    <% end %>

  <% end %>
</main>

app/views/homes/top.html.erb
<div class = "guidance mx-auto">

  <div class = "person mx-auto">
    <%= image_tag "study_chienetsu_girl.gif", :size => "100x100" %>
    <p>
      IT用語が分からなくて</br>
      勉強が捗らない
    </p>
  </div>

  <div class = "person mx-auto">
    <%= image_tag "kaiwa_hairenai_businessman.gif", :size => "100x100" %>
    <p>
      IT用語が分からなくて</br>
      会話についていけない
    </p>
  </div>

  <div class = "information mx-auto">
    <p>
      そんなあなたは、IT用語で迷子になっているかも。</br>
      IT用語を学習しましょう。
    </p>
    <button type="button" class="btn btn-outline-secondary">
      <%= link_to "新規登録", new_user_registration_path %>
    </button>
    <button type="button" class="btn btn-outline-secondary">
      <%= link_to "ログインする", new_user_session_path  %>
    </button>
  </div>

</div>

app/views/search/search.html.erb
<div class = "container">
  <main class = "mt-5 pt-1">
    <div class ="row my-5">
      <div class ="col">
        <h1>【検索結果】</h1>
      </div>
    </div>

    <div class = "mx-auto">
      <% if @it_words.present? %>
        <% @it_words.each do |it_word| %>
          <h3><%= it_word.word %></h3>
          <h3><%= it_word.body %></h3>
        <% end %>
      <% else %>
        <h3>該当するIT用語がありません。</h3>
        <h3>お手数ですがIT用語新規登録より登録お願いします。</h3>
      <% end %>
    </div>