config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/choice'
  devise_for :users
  get '/search' => 'search#search'
  resource :study_counts, only: [:create]
  get '/dangers' => 'dangers#index'
  get '/category' => 'categories#category'

  # collection以降、学習機能実装時、URL要確認
  resources :it_words do
    collection do
      get 'start'
      get 'finish'
      get 'quiz'
      get 'category_quiz'
    end
    member do
      get 'category_show'
    end
    resources :bookmarks, only: %i[create destroy]
    resources :dangers, only: %i[create destroy]
  end

  resources :users, only: %i[index edit update destroy show] do
    member do
      get '/bookmarks' => 'bookmarks#index'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # 引数で渡されたユーザidがBookmarksテーブル内に存在（exists?）するかどうかを調べる
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :it_words, dependent: :destroy
end

app/models/danger.rb
class Danger < ApplicationRecord
  belongs_to :user
  belongs_to :it_word
end

app/models/it_word.rb
class ItWord < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy

  validates :word, presence: true
  validates :body, presence: true

  # 引数で渡されたユーザidがDangersテーブル内に存在（exists?）するかどうかを調べる
  def dangered_by?(user)
    dangers.where(user_id: user.id).exists?
  end

  # searchの定義
  def self.search(search)
    ItWord.where(['word LIKE ?', "%#{search}%"])
  end
end

app/models/study_count.rb
class StudyCount < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :it_words, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :dangers, dependent: :destroy
  has_many :study_counts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/dangers_controller.rb
class DangersController < ApplicationController
  def create
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.new(it_word_id: @it_word.id)
    danger.save
  end

  def destroy
    @it_word = ItWord.find(params[:it_word_id])
    danger = current_user.dangers.find_by(it_word_id: @it_word.id)
    danger.destroy
  end

  def index
    @dangers = Danger.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def choice
    @it_words = ItWord.all
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @it_words = ItWord.search(params[:search])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    # エラーメッセージ表示の為、インスタンス変数
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      # 元々のデータ渡す必要が無いから、インスタンス変数渡さなくていい
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/'
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dangers_helper.rb
module DangersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/it_words_helper.rb
module ItWordsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/study_counts_helper.rb
module StudyCountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <title>MAITAN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--viewport設定 レスポンシブ-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <!--fontawesome読み込み-->
    <script src="https://kit.fontawesome.com/62ec8234bf.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!--ヘッダーレイアウト-->
    <% if user_signed_in? %>
      <header>
        <div class="container">
          <nav class="navbar navbar-expand-lg"  >
            <a href="/homes/choice" class="rogo"><%= image_tag "logo.png", :size => "100x100" %></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <button class="btn btn-light" type="button">
                    <%= link_to "IT用語新規登録", new_it_word_path %>
                  </button>
                </li>
                <li class="nav-item active">
                  <button class="btn btn-light" type="button">
                    <%= link_to "IT用語一覧", it_words_path %>
                  </button>
                </li>
                <li class="nav-item active">
                  <button class="btn btn-light" type="button">
                    <%= link_to "マイページ", user_path(current_user) %>
                  </button>
                </li>
                <li class="nav-item active">
                  <button class="btn btn-light" type="button">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                  </button>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
    <% end %>

    <%= yield %>

  </body>
</html>